name: Release Build
on:
  push:
    tags:
    - 'v*'
jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
        node-registry: ['https://registry.npmjs.org']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test --if-present
        npm run electron:build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset For Win
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WEICAI_VERSION: 0.1.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist_electron/微采助手 Setup ${{ WEICAI_VERSION }}.exe
        asset_name: 微采助手-Setup
        asset_content_type: application/x-executable 